### ISSUE TITLE
Python3?

### ISSUE THREAD

**Issue by stevemolloy** [archman/pyrpn#2]
This package is only available on PyPI for Python2.7.  Are there any major issues that would prevent an easy update of this to work with Python3?
(I'm more than willing to help with the update if it's possible.)

**Comment by archman** [comment]
Everything should work fine with Python 3, I've just updated with Python 3.5 and 3.6 unittests, along with 2.7, see 3d2b480a278c36a03ee2648e46be281714fe79a4. Any contribution is welcomed, so please feel free to make it better, and please send back with PRs, thanks.

**Comment by stevemolloy** [comment]
Great. It's working in 3.6 now.  Thanks for the fast response!
